language: node_js
node_js:
- node
cache:
  directories:
  - node_modules
env:
  global:
    secure: v27gk6mp8pj5LbyFiExhhfye0bmrQQX6yUlHvsUH2HYIY5mDVOcMPAgVKQatMaeEnu/qpavWflDuEj8iwSfd3buLJK88ePw1Hk9SUPNsShmYjE2wuS7iCW+s2oRqnrRC+ik4BRqmb18CU2NOVAOk7FBnnT/3GtLneGqqUsP/UzTrlJ8bZbzjoa60bOJJg78WVQGWr6USY5NiPNWa3ORHpTa9urj5Dnr4Q9KJHgWWMYonr5XyQWG4bpOusJ3vv12+Mkm5m5gnNl7FAeIPPOPwkg2oOJ9KPpunaMNdAp1ud0c4+O2BsjVMG28hhE5ySws6VLuKKGClVhVJK+spfVlycF37mgzU1mgQd1Ufsm8d7IzMN68gJhRsxE7Y4rHTFp4QSJEBWLkxhHuYCBNge3a/otd4fI4qXupYsikpR/8f+hwKVi3bn1+tO7MbcUVF17uo3Z2yEzwKNp76OtUTE7G/+W4sXeOdLG/PAAyIRoastT1XchgTNk29L9v75VLHozahFb9KTmIHikHZegVw22Pe9INN7HxPM8/OkTETYYvS4k/lJ9PJ9qZP9rVVmIH6fclsCZoPyp20DLXtW1XZBB+VF8W0anPcpsHguCTh50n4gkxKcNC43etdkAUb1Hg7mwrxOhhLRu+JntaeHZAofTyX26F24z1UgizhAoYg3V1cCPc=
